package com.pokemon.game;

public enum TriggerBoxEnum {

    NONE,

    //Labor
    TRIGGER_BOX_G_LABOR_1,
    TRIGGER_BOX_LABOR_INNEN,

    //Starterhaus
    TRIGGER_BOX_START_INNEN,
    TRIGGER_BOX_G_START_1,

    //EER
    TRIGGER_BOX_EER_INNEN,
    TRIGGER_BOX_G_EER_1,

    // Arena
    TRIGGER_BOX_ARENA_INNEN,
    TRIGGER_BOX_G_ARENA_11,
    TRIGGER_BOX_G_ARENA_12,
    TRIGGER_BOX_G_ARENA_13,
    TRIGGER_BOX_G_ARENA_14,


    //Gebiet 1
    TRIGGER_BOX_LABOR_AUSSEN,
    TRIGGER_BOX_START_AUSSEN,
    TRIGGER_BOX_GEBIET1,
    TRIGGER_BOX_G_AUSSEN_1,

    //Gebiet 2
    TRIGGER_BOX_G_GEBIET2_1,
    TRIGGER_BOX_G_GEBIET2_2,
    TRIGGER_BOX_GEBIET2_1,
    TRIGGER_BOX_GEBIET2_2,
    TRIGGER_BOX_EER_AUSSEN,

    //Gebiet 3
    TRIGGER_BOX_GEBIET3_1,
    TRIGGER_BOX_ARENA_AUSSEN,

}
