package com.pokemon.game;

public enum TriggerBoxEnum {
    NONE,
    TRIGGER_BOX_LABOR_AUSSEN,
    TRIGGER_BOX_LABOR_INNEN,
    TRIGGER_BOX_G_LABOR_1,
    TRIGGER_BOX_START_INNEN,
    TRIGGER_BOX_G_START_1,
    TRIGGER_BOX_G_OUTSIDE_1,
    TRIGGER_BOX_1,
    TRIGGER_BOX_PLACEHOLDER_1,


}
